version: '3'
services:
  python:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'abc-discord-bot'
    working_dir: '/abc-discord-bot'
    tty: true
    volumes:
      - ./:/abc-discord-bot
